services:
  - type: web
    name: n8n
    env: node
    plan: free
    branch: master
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile
    startCommand: pnpm start
    envVars:
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
